name: CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.alirzarezaee }}
          password: ${{ secrets.1q2w3?123 }}

      - name: Build and Push Docker image
        run: |
          docker build -t your-dockerhub-username/django-app:latest .
          docker push your-dockerhub-username/django-app:latest

      - name: Deploy to Server
        run: |
          ssh username@your-server-ip "docker pull your-dockerhub-username/django-app:latest && docker stop django-app || true && docker rm django-app || true && docker run -d --name django-app -p 8000:8000 your-dockerhub-username/django-app:latest"
