name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    
      
    - name: Generate Image Tag
      id: generate_tag
      run: |
        tag=$(date +%Y%m%d)-${{ github.run_number }}
        echo "IMAGE_TAG=$tag" >> $GITHUB_ENV

    - name: Build Backend Docker image
      run: docker build -t backend:${{ env.IMAGE_TAG }} .

    - name: Save Docker image to file
      run: docker save -o backend.tar backend:${{ env.IMAGE_TAG }}

    - name: Upload Docker image as artifact
      uses: actions/upload-artifact@v3
      with:
        name: docker-image
        path: backend.tar

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Download Docker image artifact
      uses: actions/download-artifact@v3
      with:
        name: docker-image
        path: backend.tar

    - name: Test SSH Connection
      env:
        SSH_HOST: ${{ secrets.SERVER_HOST }}
        SSH_USERNAME: ${{ secrets.SERVER_USER }}
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      run: |
        echo "${SSH_PRIVATE_KEY}" > /tmp/private_key
        chmod 600 /tmp/private_key
        ssh -v -o StrictHostKeyChecking=no -i /tmp/private_key ${SSH_USERNAME}@${SSH_HOST} "echo 'SSH connection successful'"

    - name: Upload Docker image to server
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.SERVER_PORT }}
        source: "backend.tar"
        target: "/home/ubuntu/build_deploy/"

    - name: Deploy Docker image on server
      env:
        SSH_HOST: ${{ secrets.SERVER_HOST }}
        SSH_USERNAME: ${{ secrets.SERVER_USER }}
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      run: |
        echo "${SSH_PRIVATE_KEY}" > /tmp/private_key
        chmod 600 /tmp/private_key
        ssh -o StrictHostKeyChecking=no -i /tmp/private_key ${SSH_USERNAME}@${SSH_HOST} << EOF
          docker load -i /home/ubuntu/build_deploy/backend.tar/backend.tar
          cd /home/ubuntu/project
          sudo sed -i 's|image: backend:.*|image: backend:${{ env.IMAGE_TAG }}|' docker-compose.yml
          docker-compose up -d
        EOF
      shell: bash
